// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlmhhzkryvgskdhrxucy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsbWhoemtyeXZnc2tkaHJ4dWN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4Nzk2NTEsImV4cCI6MjA3NDQ1NTY1MX0.Ul25dOkYA_STU3xrcG5Xp4eTIUZ9eFgpUodKMfun0v0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});